// Code generated by Prisma (prisma@1.17.1). DO NOT EDIT.
// Please don't change this file manually but run `prisma generate` to update it.
// For more information, please read the docs: https://www.prisma.io/docs/prisma-client/

import { GraphQLSchema } from "graphql";
import { IResolvers } from "graphql-tools/dist/Interfaces";
import { makePrismaClientClass, BaseClientOptions } from "prisma-client-lib";
import { typeDefs } from "./prisma-schema";

type AtLeastOne<T, U = { [K in keyof T]: Pick<T, K> }> = Partial<T> &
  U[keyof U];

export interface Exists {
  investment: (where?: InvestmentWhereInput) => Promise<boolean>;
  providers: (where?: ProvidersWhereInput) => Promise<boolean>;
}

export interface Node {}

export interface Fragmentable {
  $fragment<T>(fragment: string | Object): T;
}

export interface Prisma {
  $exists: Exists;
  $graphql: <T = any>(
    query: string,
    variables?: { [key: string]: any }
  ) => Promise<T>;
  $getAbstractResolvers(filterSchema?: GraphQLSchema | string): IResolvers;

  /**
   * Queries
   */

  investment: (where: InvestmentWhereUniqueInput) => Investment;
  investments: (
    args?: {
      where?: InvestmentWhereInput;
      orderBy?: InvestmentOrderByInput;
      skip?: Int;
      after?: String;
      before?: String;
      first?: Int;
      last?: Int;
    }
  ) => Promise<Array<InvestmentNode>>;
  investmentsConnection: (
    args?: {
      where?: InvestmentWhereInput;
      orderBy?: InvestmentOrderByInput;
      skip?: Int;
      after?: String;
      before?: String;
      first?: Int;
      last?: Int;
    }
  ) => InvestmentConnection;
  providers: (where: ProvidersWhereUniqueInput) => Providers;
  providerses: (
    args?: {
      where?: ProvidersWhereInput;
      orderBy?: ProvidersOrderByInput;
      skip?: Int;
      after?: String;
      before?: String;
      first?: Int;
      last?: Int;
    }
  ) => Promise<Array<ProvidersNode>>;
  providersesConnection: (
    args?: {
      where?: ProvidersWhereInput;
      orderBy?: ProvidersOrderByInput;
      skip?: Int;
      after?: String;
      before?: String;
      first?: Int;
      last?: Int;
    }
  ) => ProvidersConnection;
  node: (args: { id: ID_Output }) => Node;

  /**
   * Mutations
   */

  createInvestment: (data: InvestmentCreateInput) => Investment;
  updateInvestment: (
    args: { data: InvestmentUpdateInput; where: InvestmentWhereUniqueInput }
  ) => Investment;
  updateManyInvestments: (
    args: { data: InvestmentUpdateInput; where?: InvestmentWhereInput }
  ) => BatchPayload;
  upsertInvestment: (
    args: {
      where: InvestmentWhereUniqueInput;
      create: InvestmentCreateInput;
      update: InvestmentUpdateInput;
    }
  ) => Investment;
  deleteInvestment: (where: InvestmentWhereUniqueInput) => Investment;
  deleteManyInvestments: (where?: InvestmentWhereInput) => BatchPayload;
  createProviders: (data: ProvidersCreateInput) => Providers;
  updateProviders: (
    args: { data: ProvidersUpdateInput; where: ProvidersWhereUniqueInput }
  ) => Providers;
  updateManyProviderses: (
    args: { data: ProvidersUpdateInput; where?: ProvidersWhereInput }
  ) => BatchPayload;
  upsertProviders: (
    args: {
      where: ProvidersWhereUniqueInput;
      create: ProvidersCreateInput;
      update: ProvidersUpdateInput;
    }
  ) => Providers;
  deleteProviders: (where: ProvidersWhereUniqueInput) => Providers;
  deleteManyProviderses: (where?: ProvidersWhereInput) => BatchPayload;

  /**
   * Subscriptions
   */

  $subscribe: Subscription;
}

export interface Subscription {
  investment: (
    where?: InvestmentSubscriptionWhereInput
  ) => InvestmentSubscriptionPayloadSubscription;
  providers: (
    where?: ProvidersSubscriptionWhereInput
  ) => ProvidersSubscriptionPayloadSubscription;
}

export interface ClientConstructor<T> {
  new (options?: BaseClientOptions): T;
}

/**
 * Types
 */

export type InvestmentOrderByInput =
  | "id_ASC"
  | "id_DESC"
  | "address_ASC"
  | "address_DESC"
  | "price_ASC"
  | "price_DESC"
  | "lease_ASC"
  | "lease_DESC"
  | "createdAt_ASC"
  | "createdAt_DESC"
  | "updatedAt_ASC"
  | "updatedAt_DESC";

export type ProvidersOrderByInput =
  | "id_ASC"
  | "id_DESC"
  | "name_ASC"
  | "name_DESC"
  | "createdAt_ASC"
  | "createdAt_DESC"
  | "updatedAt_ASC"
  | "updatedAt_DESC";

export type MutationType = "CREATED" | "UPDATED" | "DELETED";

export interface ProvidersCreateInput {
  name: String;
}

export interface ProvidersWhereInput {
  id?: ID_Input;
  id_not?: ID_Input;
  id_in?: ID_Input[] | ID_Input;
  id_not_in?: ID_Input[] | ID_Input;
  id_lt?: ID_Input;
  id_lte?: ID_Input;
  id_gt?: ID_Input;
  id_gte?: ID_Input;
  id_contains?: ID_Input;
  id_not_contains?: ID_Input;
  id_starts_with?: ID_Input;
  id_not_starts_with?: ID_Input;
  id_ends_with?: ID_Input;
  id_not_ends_with?: ID_Input;
  name?: String;
  name_not?: String;
  name_in?: String[] | String;
  name_not_in?: String[] | String;
  name_lt?: String;
  name_lte?: String;
  name_gt?: String;
  name_gte?: String;
  name_contains?: String;
  name_not_contains?: String;
  name_starts_with?: String;
  name_not_starts_with?: String;
  name_ends_with?: String;
  name_not_ends_with?: String;
  AND?: ProvidersWhereInput[] | ProvidersWhereInput;
  OR?: ProvidersWhereInput[] | ProvidersWhereInput;
  NOT?: ProvidersWhereInput[] | ProvidersWhereInput;
}

export type InvestmentWhereUniqueInput = AtLeastOne<{
  id: ID_Input;
}>;

export type ProvidersWhereUniqueInput = AtLeastOne<{
  id: ID_Input;
}>;

export interface InvestmentSubscriptionWhereInput {
  mutation_in?: MutationType[] | MutationType;
  updatedFields_contains?: String;
  updatedFields_contains_every?: String[] | String;
  updatedFields_contains_some?: String[] | String;
  node?: InvestmentWhereInput;
  AND?: InvestmentSubscriptionWhereInput[] | InvestmentSubscriptionWhereInput;
  OR?: InvestmentSubscriptionWhereInput[] | InvestmentSubscriptionWhereInput;
  NOT?: InvestmentSubscriptionWhereInput[] | InvestmentSubscriptionWhereInput;
}

export interface InvestmentCreateInput {
  address: String;
  price?: Float;
  lease?: Float;
}

export interface InvestmentUpdateInput {
  address?: String;
  price?: Float;
  lease?: Float;
}

export interface ProvidersSubscriptionWhereInput {
  mutation_in?: MutationType[] | MutationType;
  updatedFields_contains?: String;
  updatedFields_contains_every?: String[] | String;
  updatedFields_contains_some?: String[] | String;
  node?: ProvidersWhereInput;
  AND?: ProvidersSubscriptionWhereInput[] | ProvidersSubscriptionWhereInput;
  OR?: ProvidersSubscriptionWhereInput[] | ProvidersSubscriptionWhereInput;
  NOT?: ProvidersSubscriptionWhereInput[] | ProvidersSubscriptionWhereInput;
}

export interface ProvidersUpdateInput {
  name?: String;
}

export interface InvestmentWhereInput {
  id?: ID_Input;
  id_not?: ID_Input;
  id_in?: ID_Input[] | ID_Input;
  id_not_in?: ID_Input[] | ID_Input;
  id_lt?: ID_Input;
  id_lte?: ID_Input;
  id_gt?: ID_Input;
  id_gte?: ID_Input;
  id_contains?: ID_Input;
  id_not_contains?: ID_Input;
  id_starts_with?: ID_Input;
  id_not_starts_with?: ID_Input;
  id_ends_with?: ID_Input;
  id_not_ends_with?: ID_Input;
  address?: String;
  address_not?: String;
  address_in?: String[] | String;
  address_not_in?: String[] | String;
  address_lt?: String;
  address_lte?: String;
  address_gt?: String;
  address_gte?: String;
  address_contains?: String;
  address_not_contains?: String;
  address_starts_with?: String;
  address_not_starts_with?: String;
  address_ends_with?: String;
  address_not_ends_with?: String;
  price?: Float;
  price_not?: Float;
  price_in?: Float[] | Float;
  price_not_in?: Float[] | Float;
  price_lt?: Float;
  price_lte?: Float;
  price_gt?: Float;
  price_gte?: Float;
  lease?: Float;
  lease_not?: Float;
  lease_in?: Float[] | Float;
  lease_not_in?: Float[] | Float;
  lease_lt?: Float;
  lease_lte?: Float;
  lease_gt?: Float;
  lease_gte?: Float;
  AND?: InvestmentWhereInput[] | InvestmentWhereInput;
  OR?: InvestmentWhereInput[] | InvestmentWhereInput;
  NOT?: InvestmentWhereInput[] | InvestmentWhereInput;
}

export interface NodeNode {
  id: ID_Output;
}

export interface ProvidersConnectionNode {}

export interface ProvidersConnection
  extends Promise<ProvidersConnectionNode>,
    Fragmentable {
  pageInfo: <T = PageInfo>() => T;
  edges: <T = Promise<Array<ProvidersEdgeNode>>>() => T;
  aggregate: <T = AggregateProviders>() => T;
}

export interface ProvidersConnectionSubscription
  extends Promise<AsyncIterator<ProvidersConnectionNode>>,
    Fragmentable {
  pageInfo: <T = PageInfoSubscription>() => T;
  edges: <T = Promise<AsyncIterator<Array<ProvidersEdgeSubscription>>>>() => T;
  aggregate: <T = AggregateProvidersSubscription>() => T;
}

export interface ProvidersPreviousValuesNode {
  id: ID_Output;
  name: String;
}

export interface ProvidersPreviousValues
  extends Promise<ProvidersPreviousValuesNode>,
    Fragmentable {
  id: () => Promise<ID_Output>;
  name: () => Promise<String>;
}

export interface ProvidersPreviousValuesSubscription
  extends Promise<AsyncIterator<ProvidersPreviousValuesNode>>,
    Fragmentable {
  id: () => Promise<AsyncIterator<ID_Output>>;
  name: () => Promise<AsyncIterator<String>>;
}

export interface ProvidersNode {
  id: ID_Output;
  name: String;
}

export interface Providers extends Promise<ProvidersNode>, Fragmentable {
  id: () => Promise<ID_Output>;
  name: () => Promise<String>;
}

export interface ProvidersSubscription
  extends Promise<AsyncIterator<ProvidersNode>>,
    Fragmentable {
  id: () => Promise<AsyncIterator<ID_Output>>;
  name: () => Promise<AsyncIterator<String>>;
}

export interface BatchPayloadNode {
  count: Long;
}

export interface BatchPayload extends Promise<BatchPayloadNode>, Fragmentable {
  count: () => Promise<Long>;
}

export interface BatchPayloadSubscription
  extends Promise<AsyncIterator<BatchPayloadNode>>,
    Fragmentable {
  count: () => Promise<AsyncIterator<Long>>;
}

export interface InvestmentSubscriptionPayloadNode {
  mutation: MutationType;
  updatedFields?: String[];
}

export interface InvestmentSubscriptionPayload
  extends Promise<InvestmentSubscriptionPayloadNode>,
    Fragmentable {
  mutation: () => Promise<MutationType>;
  node: <T = Investment>() => T;
  updatedFields: () => Promise<String[]>;
  previousValues: <T = InvestmentPreviousValues>() => T;
}

export interface InvestmentSubscriptionPayloadSubscription
  extends Promise<AsyncIterator<InvestmentSubscriptionPayloadNode>>,
    Fragmentable {
  mutation: () => Promise<AsyncIterator<MutationType>>;
  node: <T = InvestmentSubscription>() => T;
  updatedFields: () => Promise<AsyncIterator<String[]>>;
  previousValues: <T = InvestmentPreviousValuesSubscription>() => T;
}

export interface InvestmentConnectionNode {}

export interface InvestmentConnection
  extends Promise<InvestmentConnectionNode>,
    Fragmentable {
  pageInfo: <T = PageInfo>() => T;
  edges: <T = Promise<Array<InvestmentEdgeNode>>>() => T;
  aggregate: <T = AggregateInvestment>() => T;
}

export interface InvestmentConnectionSubscription
  extends Promise<AsyncIterator<InvestmentConnectionNode>>,
    Fragmentable {
  pageInfo: <T = PageInfoSubscription>() => T;
  edges: <T = Promise<AsyncIterator<Array<InvestmentEdgeSubscription>>>>() => T;
  aggregate: <T = AggregateInvestmentSubscription>() => T;
}

export interface InvestmentPreviousValuesNode {
  id: ID_Output;
  address: String;
  price?: Float;
  lease?: Float;
}

export interface InvestmentPreviousValues
  extends Promise<InvestmentPreviousValuesNode>,
    Fragmentable {
  id: () => Promise<ID_Output>;
  address: () => Promise<String>;
  price: () => Promise<Float>;
  lease: () => Promise<Float>;
}

export interface InvestmentPreviousValuesSubscription
  extends Promise<AsyncIterator<InvestmentPreviousValuesNode>>,
    Fragmentable {
  id: () => Promise<AsyncIterator<ID_Output>>;
  address: () => Promise<AsyncIterator<String>>;
  price: () => Promise<AsyncIterator<Float>>;
  lease: () => Promise<AsyncIterator<Float>>;
}

export interface InvestmentNode {
  id: ID_Output;
  address: String;
  price?: Float;
  lease?: Float;
}

export interface Investment extends Promise<InvestmentNode>, Fragmentable {
  id: () => Promise<ID_Output>;
  address: () => Promise<String>;
  price: () => Promise<Float>;
  lease: () => Promise<Float>;
}

export interface InvestmentSubscription
  extends Promise<AsyncIterator<InvestmentNode>>,
    Fragmentable {
  id: () => Promise<AsyncIterator<ID_Output>>;
  address: () => Promise<AsyncIterator<String>>;
  price: () => Promise<AsyncIterator<Float>>;
  lease: () => Promise<AsyncIterator<Float>>;
}

export interface ProvidersEdgeNode {
  cursor: String;
}

export interface ProvidersEdge
  extends Promise<ProvidersEdgeNode>,
    Fragmentable {
  node: <T = Providers>() => T;
  cursor: () => Promise<String>;
}

export interface ProvidersEdgeSubscription
  extends Promise<AsyncIterator<ProvidersEdgeNode>>,
    Fragmentable {
  node: <T = ProvidersSubscription>() => T;
  cursor: () => Promise<AsyncIterator<String>>;
}

export interface AggregateInvestmentNode {
  count: Int;
}

export interface AggregateInvestment
  extends Promise<AggregateInvestmentNode>,
    Fragmentable {
  count: () => Promise<Int>;
}

export interface AggregateInvestmentSubscription
  extends Promise<AsyncIterator<AggregateInvestmentNode>>,
    Fragmentable {
  count: () => Promise<AsyncIterator<Int>>;
}

export interface AggregateProvidersNode {
  count: Int;
}

export interface AggregateProviders
  extends Promise<AggregateProvidersNode>,
    Fragmentable {
  count: () => Promise<Int>;
}

export interface AggregateProvidersSubscription
  extends Promise<AsyncIterator<AggregateProvidersNode>>,
    Fragmentable {
  count: () => Promise<AsyncIterator<Int>>;
}

export interface PageInfoNode {
  hasNextPage: Boolean;
  hasPreviousPage: Boolean;
  startCursor?: String;
  endCursor?: String;
}

export interface PageInfo extends Promise<PageInfoNode>, Fragmentable {
  hasNextPage: () => Promise<Boolean>;
  hasPreviousPage: () => Promise<Boolean>;
  startCursor: () => Promise<String>;
  endCursor: () => Promise<String>;
}

export interface PageInfoSubscription
  extends Promise<AsyncIterator<PageInfoNode>>,
    Fragmentable {
  hasNextPage: () => Promise<AsyncIterator<Boolean>>;
  hasPreviousPage: () => Promise<AsyncIterator<Boolean>>;
  startCursor: () => Promise<AsyncIterator<String>>;
  endCursor: () => Promise<AsyncIterator<String>>;
}

export interface ProvidersSubscriptionPayloadNode {
  mutation: MutationType;
  updatedFields?: String[];
}

export interface ProvidersSubscriptionPayload
  extends Promise<ProvidersSubscriptionPayloadNode>,
    Fragmentable {
  mutation: () => Promise<MutationType>;
  node: <T = Providers>() => T;
  updatedFields: () => Promise<String[]>;
  previousValues: <T = ProvidersPreviousValues>() => T;
}

export interface ProvidersSubscriptionPayloadSubscription
  extends Promise<AsyncIterator<ProvidersSubscriptionPayloadNode>>,
    Fragmentable {
  mutation: () => Promise<AsyncIterator<MutationType>>;
  node: <T = ProvidersSubscription>() => T;
  updatedFields: () => Promise<AsyncIterator<String[]>>;
  previousValues: <T = ProvidersPreviousValuesSubscription>() => T;
}

export interface InvestmentEdgeNode {
  cursor: String;
}

export interface InvestmentEdge
  extends Promise<InvestmentEdgeNode>,
    Fragmentable {
  node: <T = Investment>() => T;
  cursor: () => Promise<String>;
}

export interface InvestmentEdgeSubscription
  extends Promise<AsyncIterator<InvestmentEdgeNode>>,
    Fragmentable {
  node: <T = InvestmentSubscription>() => T;
  cursor: () => Promise<AsyncIterator<String>>;
}

export type Long = string;

/*
The `ID` scalar type represents a unique identifier, often used to refetch an object or as key for a cache. The ID type appears in a JSON response as a String; however, it is not intended to be human-readable. When expected as an input type, any string (such as `"4"`) or integer (such as `4`) input value will be accepted as an ID.
*/
export type ID_Input = string | number;
export type ID_Output = string;

/*
The `Boolean` scalar type represents `true` or `false`.
*/
export type Boolean = boolean;

/*
The `Int` scalar type represents non-fractional signed whole numeric values. Int can represent values between -(2^31) and 2^31 - 1. 
*/
export type Int = number;

/*
The `Float` scalar type represents signed double-precision fractional values as specified by [IEEE 754](http://en.wikipedia.org/wiki/IEEE_floating_point). 
*/
export type Float = number;

/*
The `String` scalar type represents textual data, represented as UTF-8 character sequences. The String type is most often used by GraphQL to represent free-form human-readable text.
*/
export type String = string;

/**
 * Type Defs
 */

export const Prisma = makePrismaClientClass<ClientConstructor<Prisma>>({
  typeDefs,
  endpoint: `${process.env["PRISMA_ENDPOINT"]}`
});
export const prisma = new Prisma();
