// Code generated by Prisma (prisma@1.17.1). DO NOT EDIT.
// Please don't change this file manually but run `prisma generate` to update it.
// For more information, please read the docs: https://www.prisma.io/docs/prisma-client/

import { GraphQLSchema } from "graphql";
import { IResolvers } from "graphql-tools/dist/Interfaces";
import { makePrismaClientClass, BaseClientOptions } from "prisma-client-lib";
import { typeDefs } from "./prisma-schema";

type AtLeastOne<T, U = { [K in keyof T]: Pick<T, K> }> = Partial<T> &
  U[keyof U];

export interface Exists {
  investment: (where?: InvestmentWhereInput) => Promise<boolean>;
  provider: (where?: ProviderWhereInput) => Promise<boolean>;
  user: (where?: UserWhereInput) => Promise<boolean>;
}

export interface Node {}

export interface Fragmentable {
  $fragment<T>(fragment: string | Object): T;
}

export interface Prisma {
  $exists: Exists;
  $graphql: <T = any>(
    query: string,
    variables?: { [key: string]: any }
  ) => Promise<T>;
  $getAbstractResolvers(filterSchema?: GraphQLSchema | string): IResolvers;

  /**
   * Queries
   */

  investment: (where: InvestmentWhereUniqueInput) => Investment;
  investments: (
    args?: {
      where?: InvestmentWhereInput;
      orderBy?: InvestmentOrderByInput;
      skip?: Int;
      after?: String;
      before?: String;
      first?: Int;
      last?: Int;
    }
  ) => Promise<Array<InvestmentNode>>;
  investmentsConnection: (
    args?: {
      where?: InvestmentWhereInput;
      orderBy?: InvestmentOrderByInput;
      skip?: Int;
      after?: String;
      before?: String;
      first?: Int;
      last?: Int;
    }
  ) => InvestmentConnection;
  provider: (where: ProviderWhereUniqueInput) => Provider;
  providers: (
    args?: {
      where?: ProviderWhereInput;
      orderBy?: ProviderOrderByInput;
      skip?: Int;
      after?: String;
      before?: String;
      first?: Int;
      last?: Int;
    }
  ) => Promise<Array<ProviderNode>>;
  providersConnection: (
    args?: {
      where?: ProviderWhereInput;
      orderBy?: ProviderOrderByInput;
      skip?: Int;
      after?: String;
      before?: String;
      first?: Int;
      last?: Int;
    }
  ) => ProviderConnection;
  user: (where: UserWhereUniqueInput) => User;
  users: (
    args?: {
      where?: UserWhereInput;
      orderBy?: UserOrderByInput;
      skip?: Int;
      after?: String;
      before?: String;
      first?: Int;
      last?: Int;
    }
  ) => Promise<Array<UserNode>>;
  usersConnection: (
    args?: {
      where?: UserWhereInput;
      orderBy?: UserOrderByInput;
      skip?: Int;
      after?: String;
      before?: String;
      first?: Int;
      last?: Int;
    }
  ) => UserConnection;
  node: (args: { id: ID_Output }) => Node;

  /**
   * Mutations
   */

  createInvestment: (data: InvestmentCreateInput) => Investment;
  updateInvestment: (
    args: { data: InvestmentUpdateInput; where: InvestmentWhereUniqueInput }
  ) => Investment;
  updateManyInvestments: (
    args: { data: InvestmentUpdateInput; where?: InvestmentWhereInput }
  ) => BatchPayload;
  upsertInvestment: (
    args: {
      where: InvestmentWhereUniqueInput;
      create: InvestmentCreateInput;
      update: InvestmentUpdateInput;
    }
  ) => Investment;
  deleteInvestment: (where: InvestmentWhereUniqueInput) => Investment;
  deleteManyInvestments: (where?: InvestmentWhereInput) => BatchPayload;
  createProvider: (data: ProviderCreateInput) => Provider;
  updateProvider: (
    args: { data: ProviderUpdateInput; where: ProviderWhereUniqueInput }
  ) => Provider;
  updateManyProviders: (
    args: { data: ProviderUpdateInput; where?: ProviderWhereInput }
  ) => BatchPayload;
  upsertProvider: (
    args: {
      where: ProviderWhereUniqueInput;
      create: ProviderCreateInput;
      update: ProviderUpdateInput;
    }
  ) => Provider;
  deleteProvider: (where: ProviderWhereUniqueInput) => Provider;
  deleteManyProviders: (where?: ProviderWhereInput) => BatchPayload;
  createUser: (data: UserCreateInput) => User;
  updateUser: (
    args: { data: UserUpdateInput; where: UserWhereUniqueInput }
  ) => User;
  updateManyUsers: (
    args: { data: UserUpdateInput; where?: UserWhereInput }
  ) => BatchPayload;
  upsertUser: (
    args: {
      where: UserWhereUniqueInput;
      create: UserCreateInput;
      update: UserUpdateInput;
    }
  ) => User;
  deleteUser: (where: UserWhereUniqueInput) => User;
  deleteManyUsers: (where?: UserWhereInput) => BatchPayload;

  /**
   * Subscriptions
   */

  $subscribe: Subscription;
}

export interface Subscription {
  investment: (
    where?: InvestmentSubscriptionWhereInput
  ) => InvestmentSubscriptionPayloadSubscription;
  provider: (
    where?: ProviderSubscriptionWhereInput
  ) => ProviderSubscriptionPayloadSubscription;
  user: (
    where?: UserSubscriptionWhereInput
  ) => UserSubscriptionPayloadSubscription;
}

export interface ClientConstructor<T> {
  new (options?: BaseClientOptions): T;
}

/**
 * Types
 */

export type InvestmentOrderByInput =
  | "id_ASC"
  | "id_DESC"
  | "address_ASC"
  | "address_DESC"
  | "price_ASC"
  | "price_DESC"
  | "monthly_rent_ASC"
  | "monthly_rent_DESC"
  | "mortgage_downpayment_ASC"
  | "mortgage_downpayment_DESC"
  | "mortgage_amount_ASC"
  | "mortgage_amount_DESC"
  | "mortgage_interest_rate_ASC"
  | "mortgage_interest_rate_DESC"
  | "mortgage_period_ASC"
  | "mortgage_period_DESC"
  | "createdAt_ASC"
  | "createdAt_DESC"
  | "updatedAt_ASC"
  | "updatedAt_DESC";

export type ProviderOrderByInput =
  | "id_ASC"
  | "id_DESC"
  | "name_ASC"
  | "name_DESC"
  | "type_ASC"
  | "type_DESC"
  | "rate_ASC"
  | "rate_DESC"
  | "review_number_ASC"
  | "review_number_DESC"
  | "review_ASC"
  | "review_DESC"
  | "phone_number_ASC"
  | "phone_number_DESC"
  | "email_ASC"
  | "email_DESC"
  | "addr1_ASC"
  | "addr1_DESC"
  | "addr2_ASC"
  | "addr2_DESC"
  | "createdAt_ASC"
  | "createdAt_DESC"
  | "updatedAt_ASC"
  | "updatedAt_DESC";

export type MutationType = "CREATED" | "UPDATED" | "DELETED";

export type UserOrderByInput =
  | "id_ASC"
  | "id_DESC"
  | "email_ASC"
  | "email_DESC"
  | "password_ASC"
  | "password_DESC"
  | "createdAt_ASC"
  | "createdAt_DESC"
  | "updatedAt_ASC"
  | "updatedAt_DESC";

export type InvestmentWhereUniqueInput = AtLeastOne<{
  id: ID_Input;
}>;

export type ProviderWhereUniqueInput = AtLeastOne<{
  id: ID_Input;
}>;

export type UserWhereUniqueInput = AtLeastOne<{
  id: ID_Input;
  email?: String;
}>;

export interface ProviderCreateInput {
  name: String;
  type: String;
  rate?: Float;
  review_number?: Int;
  review?: String;
  phone_number?: String;
  email?: String;
  addr1?: String;
  addr2?: String;
}

export interface InvestmentWhereInput {
  id?: ID_Input;
  id_not?: ID_Input;
  id_in?: ID_Input[] | ID_Input;
  id_not_in?: ID_Input[] | ID_Input;
  id_lt?: ID_Input;
  id_lte?: ID_Input;
  id_gt?: ID_Input;
  id_gte?: ID_Input;
  id_contains?: ID_Input;
  id_not_contains?: ID_Input;
  id_starts_with?: ID_Input;
  id_not_starts_with?: ID_Input;
  id_ends_with?: ID_Input;
  id_not_ends_with?: ID_Input;
  address?: String;
  address_not?: String;
  address_in?: String[] | String;
  address_not_in?: String[] | String;
  address_lt?: String;
  address_lte?: String;
  address_gt?: String;
  address_gte?: String;
  address_contains?: String;
  address_not_contains?: String;
  address_starts_with?: String;
  address_not_starts_with?: String;
  address_ends_with?: String;
  address_not_ends_with?: String;
  price?: Float;
  price_not?: Float;
  price_in?: Float[] | Float;
  price_not_in?: Float[] | Float;
  price_lt?: Float;
  price_lte?: Float;
  price_gt?: Float;
  price_gte?: Float;
  monthly_rent?: Float;
  monthly_rent_not?: Float;
  monthly_rent_in?: Float[] | Float;
  monthly_rent_not_in?: Float[] | Float;
  monthly_rent_lt?: Float;
  monthly_rent_lte?: Float;
  monthly_rent_gt?: Float;
  monthly_rent_gte?: Float;
  mortgage_downpayment?: Float;
  mortgage_downpayment_not?: Float;
  mortgage_downpayment_in?: Float[] | Float;
  mortgage_downpayment_not_in?: Float[] | Float;
  mortgage_downpayment_lt?: Float;
  mortgage_downpayment_lte?: Float;
  mortgage_downpayment_gt?: Float;
  mortgage_downpayment_gte?: Float;
  mortgage_amount?: Float;
  mortgage_amount_not?: Float;
  mortgage_amount_in?: Float[] | Float;
  mortgage_amount_not_in?: Float[] | Float;
  mortgage_amount_lt?: Float;
  mortgage_amount_lte?: Float;
  mortgage_amount_gt?: Float;
  mortgage_amount_gte?: Float;
  mortgage_interest_rate?: Float;
  mortgage_interest_rate_not?: Float;
  mortgage_interest_rate_in?: Float[] | Float;
  mortgage_interest_rate_not_in?: Float[] | Float;
  mortgage_interest_rate_lt?: Float;
  mortgage_interest_rate_lte?: Float;
  mortgage_interest_rate_gt?: Float;
  mortgage_interest_rate_gte?: Float;
  mortgage_period?: Float;
  mortgage_period_not?: Float;
  mortgage_period_in?: Float[] | Float;
  mortgage_period_not_in?: Float[] | Float;
  mortgage_period_lt?: Float;
  mortgage_period_lte?: Float;
  mortgage_period_gt?: Float;
  mortgage_period_gte?: Float;
  AND?: InvestmentWhereInput[] | InvestmentWhereInput;
  OR?: InvestmentWhereInput[] | InvestmentWhereInput;
  NOT?: InvestmentWhereInput[] | InvestmentWhereInput;
}

export interface ProviderWhereInput {
  id?: ID_Input;
  id_not?: ID_Input;
  id_in?: ID_Input[] | ID_Input;
  id_not_in?: ID_Input[] | ID_Input;
  id_lt?: ID_Input;
  id_lte?: ID_Input;
  id_gt?: ID_Input;
  id_gte?: ID_Input;
  id_contains?: ID_Input;
  id_not_contains?: ID_Input;
  id_starts_with?: ID_Input;
  id_not_starts_with?: ID_Input;
  id_ends_with?: ID_Input;
  id_not_ends_with?: ID_Input;
  name?: String;
  name_not?: String;
  name_in?: String[] | String;
  name_not_in?: String[] | String;
  name_lt?: String;
  name_lte?: String;
  name_gt?: String;
  name_gte?: String;
  name_contains?: String;
  name_not_contains?: String;
  name_starts_with?: String;
  name_not_starts_with?: String;
  name_ends_with?: String;
  name_not_ends_with?: String;
  type?: String;
  type_not?: String;
  type_in?: String[] | String;
  type_not_in?: String[] | String;
  type_lt?: String;
  type_lte?: String;
  type_gt?: String;
  type_gte?: String;
  type_contains?: String;
  type_not_contains?: String;
  type_starts_with?: String;
  type_not_starts_with?: String;
  type_ends_with?: String;
  type_not_ends_with?: String;
  rate?: Float;
  rate_not?: Float;
  rate_in?: Float[] | Float;
  rate_not_in?: Float[] | Float;
  rate_lt?: Float;
  rate_lte?: Float;
  rate_gt?: Float;
  rate_gte?: Float;
  review_number?: Int;
  review_number_not?: Int;
  review_number_in?: Int[] | Int;
  review_number_not_in?: Int[] | Int;
  review_number_lt?: Int;
  review_number_lte?: Int;
  review_number_gt?: Int;
  review_number_gte?: Int;
  review?: String;
  review_not?: String;
  review_in?: String[] | String;
  review_not_in?: String[] | String;
  review_lt?: String;
  review_lte?: String;
  review_gt?: String;
  review_gte?: String;
  review_contains?: String;
  review_not_contains?: String;
  review_starts_with?: String;
  review_not_starts_with?: String;
  review_ends_with?: String;
  review_not_ends_with?: String;
  phone_number?: String;
  phone_number_not?: String;
  phone_number_in?: String[] | String;
  phone_number_not_in?: String[] | String;
  phone_number_lt?: String;
  phone_number_lte?: String;
  phone_number_gt?: String;
  phone_number_gte?: String;
  phone_number_contains?: String;
  phone_number_not_contains?: String;
  phone_number_starts_with?: String;
  phone_number_not_starts_with?: String;
  phone_number_ends_with?: String;
  phone_number_not_ends_with?: String;
  email?: String;
  email_not?: String;
  email_in?: String[] | String;
  email_not_in?: String[] | String;
  email_lt?: String;
  email_lte?: String;
  email_gt?: String;
  email_gte?: String;
  email_contains?: String;
  email_not_contains?: String;
  email_starts_with?: String;
  email_not_starts_with?: String;
  email_ends_with?: String;
  email_not_ends_with?: String;
  addr1?: String;
  addr1_not?: String;
  addr1_in?: String[] | String;
  addr1_not_in?: String[] | String;
  addr1_lt?: String;
  addr1_lte?: String;
  addr1_gt?: String;
  addr1_gte?: String;
  addr1_contains?: String;
  addr1_not_contains?: String;
  addr1_starts_with?: String;
  addr1_not_starts_with?: String;
  addr1_ends_with?: String;
  addr1_not_ends_with?: String;
  addr2?: String;
  addr2_not?: String;
  addr2_in?: String[] | String;
  addr2_not_in?: String[] | String;
  addr2_lt?: String;
  addr2_lte?: String;
  addr2_gt?: String;
  addr2_gte?: String;
  addr2_contains?: String;
  addr2_not_contains?: String;
  addr2_starts_with?: String;
  addr2_not_starts_with?: String;
  addr2_ends_with?: String;
  addr2_not_ends_with?: String;
  AND?: ProviderWhereInput[] | ProviderWhereInput;
  OR?: ProviderWhereInput[] | ProviderWhereInput;
  NOT?: ProviderWhereInput[] | ProviderWhereInput;
}

export interface ProviderSubscriptionWhereInput {
  mutation_in?: MutationType[] | MutationType;
  updatedFields_contains?: String;
  updatedFields_contains_every?: String[] | String;
  updatedFields_contains_some?: String[] | String;
  node?: ProviderWhereInput;
  AND?: ProviderSubscriptionWhereInput[] | ProviderSubscriptionWhereInput;
  OR?: ProviderSubscriptionWhereInput[] | ProviderSubscriptionWhereInput;
  NOT?: ProviderSubscriptionWhereInput[] | ProviderSubscriptionWhereInput;
}

export interface UserUpdateInput {
  email?: String;
  password?: String;
}

export interface UserWhereInput {
  id?: ID_Input;
  id_not?: ID_Input;
  id_in?: ID_Input[] | ID_Input;
  id_not_in?: ID_Input[] | ID_Input;
  id_lt?: ID_Input;
  id_lte?: ID_Input;
  id_gt?: ID_Input;
  id_gte?: ID_Input;
  id_contains?: ID_Input;
  id_not_contains?: ID_Input;
  id_starts_with?: ID_Input;
  id_not_starts_with?: ID_Input;
  id_ends_with?: ID_Input;
  id_not_ends_with?: ID_Input;
  email?: String;
  email_not?: String;
  email_in?: String[] | String;
  email_not_in?: String[] | String;
  email_lt?: String;
  email_lte?: String;
  email_gt?: String;
  email_gte?: String;
  email_contains?: String;
  email_not_contains?: String;
  email_starts_with?: String;
  email_not_starts_with?: String;
  email_ends_with?: String;
  email_not_ends_with?: String;
  password?: String;
  password_not?: String;
  password_in?: String[] | String;
  password_not_in?: String[] | String;
  password_lt?: String;
  password_lte?: String;
  password_gt?: String;
  password_gte?: String;
  password_contains?: String;
  password_not_contains?: String;
  password_starts_with?: String;
  password_not_starts_with?: String;
  password_ends_with?: String;
  password_not_ends_with?: String;
  AND?: UserWhereInput[] | UserWhereInput;
  OR?: UserWhereInput[] | UserWhereInput;
  NOT?: UserWhereInput[] | UserWhereInput;
}

export interface InvestmentCreateInput {
  address: String;
  price?: Float;
  monthly_rent?: Float;
  mortgage_downpayment?: Float;
  mortgage_amount?: Float;
  mortgage_interest_rate?: Float;
  mortgage_period?: Float;
}

export interface InvestmentUpdateInput {
  address?: String;
  price?: Float;
  monthly_rent?: Float;
  mortgage_downpayment?: Float;
  mortgage_amount?: Float;
  mortgage_interest_rate?: Float;
  mortgage_period?: Float;
}

export interface UserCreateInput {
  email: String;
  password: String;
}

export interface InvestmentSubscriptionWhereInput {
  mutation_in?: MutationType[] | MutationType;
  updatedFields_contains?: String;
  updatedFields_contains_every?: String[] | String;
  updatedFields_contains_some?: String[] | String;
  node?: InvestmentWhereInput;
  AND?: InvestmentSubscriptionWhereInput[] | InvestmentSubscriptionWhereInput;
  OR?: InvestmentSubscriptionWhereInput[] | InvestmentSubscriptionWhereInput;
  NOT?: InvestmentSubscriptionWhereInput[] | InvestmentSubscriptionWhereInput;
}

export interface UserSubscriptionWhereInput {
  mutation_in?: MutationType[] | MutationType;
  updatedFields_contains?: String;
  updatedFields_contains_every?: String[] | String;
  updatedFields_contains_some?: String[] | String;
  node?: UserWhereInput;
  AND?: UserSubscriptionWhereInput[] | UserSubscriptionWhereInput;
  OR?: UserSubscriptionWhereInput[] | UserSubscriptionWhereInput;
  NOT?: UserSubscriptionWhereInput[] | UserSubscriptionWhereInput;
}

export interface ProviderUpdateInput {
  name?: String;
  type?: String;
  rate?: Float;
  review_number?: Int;
  review?: String;
  phone_number?: String;
  email?: String;
  addr1?: String;
  addr2?: String;
}

export interface NodeNode {
  id: ID_Output;
}

export interface UserEdgeNode {
  cursor: String;
}

export interface UserEdge extends Promise<UserEdgeNode>, Fragmentable {
  node: <T = User>() => T;
  cursor: () => Promise<String>;
}

export interface UserEdgeSubscription
  extends Promise<AsyncIterator<UserEdgeNode>>,
    Fragmentable {
  node: <T = UserSubscription>() => T;
  cursor: () => Promise<AsyncIterator<String>>;
}

export interface AggregateInvestmentNode {
  count: Int;
}

export interface AggregateInvestment
  extends Promise<AggregateInvestmentNode>,
    Fragmentable {
  count: () => Promise<Int>;
}

export interface AggregateInvestmentSubscription
  extends Promise<AsyncIterator<AggregateInvestmentNode>>,
    Fragmentable {
  count: () => Promise<AsyncIterator<Int>>;
}

export interface UserPreviousValuesNode {
  id: ID_Output;
  email: String;
  password: String;
}

export interface UserPreviousValues
  extends Promise<UserPreviousValuesNode>,
    Fragmentable {
  id: () => Promise<ID_Output>;
  email: () => Promise<String>;
  password: () => Promise<String>;
}

export interface UserPreviousValuesSubscription
  extends Promise<AsyncIterator<UserPreviousValuesNode>>,
    Fragmentable {
  id: () => Promise<AsyncIterator<ID_Output>>;
  email: () => Promise<AsyncIterator<String>>;
  password: () => Promise<AsyncIterator<String>>;
}

export interface InvestmentEdgeNode {
  cursor: String;
}

export interface InvestmentEdge
  extends Promise<InvestmentEdgeNode>,
    Fragmentable {
  node: <T = Investment>() => T;
  cursor: () => Promise<String>;
}

export interface InvestmentEdgeSubscription
  extends Promise<AsyncIterator<InvestmentEdgeNode>>,
    Fragmentable {
  node: <T = InvestmentSubscription>() => T;
  cursor: () => Promise<AsyncIterator<String>>;
}

export interface UserNode {
  id: ID_Output;
  email: String;
  password: String;
}

export interface User extends Promise<UserNode>, Fragmentable {
  id: () => Promise<ID_Output>;
  email: () => Promise<String>;
  password: () => Promise<String>;
}

export interface UserSubscription
  extends Promise<AsyncIterator<UserNode>>,
    Fragmentable {
  id: () => Promise<AsyncIterator<ID_Output>>;
  email: () => Promise<AsyncIterator<String>>;
  password: () => Promise<AsyncIterator<String>>;
}

export interface UserConnectionNode {}

export interface UserConnection
  extends Promise<UserConnectionNode>,
    Fragmentable {
  pageInfo: <T = PageInfo>() => T;
  edges: <T = Promise<Array<UserEdgeNode>>>() => T;
  aggregate: <T = AggregateUser>() => T;
}

export interface UserConnectionSubscription
  extends Promise<AsyncIterator<UserConnectionNode>>,
    Fragmentable {
  pageInfo: <T = PageInfoSubscription>() => T;
  edges: <T = Promise<AsyncIterator<Array<UserEdgeSubscription>>>>() => T;
  aggregate: <T = AggregateUserSubscription>() => T;
}

export interface ProviderSubscriptionPayloadNode {
  mutation: MutationType;
  updatedFields?: String[];
}

export interface ProviderSubscriptionPayload
  extends Promise<ProviderSubscriptionPayloadNode>,
    Fragmentable {
  mutation: () => Promise<MutationType>;
  node: <T = Provider>() => T;
  updatedFields: () => Promise<String[]>;
  previousValues: <T = ProviderPreviousValues>() => T;
}

export interface ProviderSubscriptionPayloadSubscription
  extends Promise<AsyncIterator<ProviderSubscriptionPayloadNode>>,
    Fragmentable {
  mutation: () => Promise<AsyncIterator<MutationType>>;
  node: <T = ProviderSubscription>() => T;
  updatedFields: () => Promise<AsyncIterator<String[]>>;
  previousValues: <T = ProviderPreviousValuesSubscription>() => T;
}

export interface AggregateUserNode {
  count: Int;
}

export interface AggregateUser
  extends Promise<AggregateUserNode>,
    Fragmentable {
  count: () => Promise<Int>;
}

export interface AggregateUserSubscription
  extends Promise<AsyncIterator<AggregateUserNode>>,
    Fragmentable {
  count: () => Promise<AsyncIterator<Int>>;
}

export interface ProviderConnectionNode {}

export interface ProviderConnection
  extends Promise<ProviderConnectionNode>,
    Fragmentable {
  pageInfo: <T = PageInfo>() => T;
  edges: <T = Promise<Array<ProviderEdgeNode>>>() => T;
  aggregate: <T = AggregateProvider>() => T;
}

export interface ProviderConnectionSubscription
  extends Promise<AsyncIterator<ProviderConnectionNode>>,
    Fragmentable {
  pageInfo: <T = PageInfoSubscription>() => T;
  edges: <T = Promise<AsyncIterator<Array<ProviderEdgeSubscription>>>>() => T;
  aggregate: <T = AggregateProviderSubscription>() => T;
}

export interface PageInfoNode {
  hasNextPage: Boolean;
  hasPreviousPage: Boolean;
  startCursor?: String;
  endCursor?: String;
}

export interface PageInfo extends Promise<PageInfoNode>, Fragmentable {
  hasNextPage: () => Promise<Boolean>;
  hasPreviousPage: () => Promise<Boolean>;
  startCursor: () => Promise<String>;
  endCursor: () => Promise<String>;
}

export interface PageInfoSubscription
  extends Promise<AsyncIterator<PageInfoNode>>,
    Fragmentable {
  hasNextPage: () => Promise<AsyncIterator<Boolean>>;
  hasPreviousPage: () => Promise<AsyncIterator<Boolean>>;
  startCursor: () => Promise<AsyncIterator<String>>;
  endCursor: () => Promise<AsyncIterator<String>>;
}

export interface BatchPayloadNode {
  count: Long;
}

export interface BatchPayload extends Promise<BatchPayloadNode>, Fragmentable {
  count: () => Promise<Long>;
}

export interface BatchPayloadSubscription
  extends Promise<AsyncIterator<BatchPayloadNode>>,
    Fragmentable {
  count: () => Promise<AsyncIterator<Long>>;
}

export interface InvestmentConnectionNode {}

export interface InvestmentConnection
  extends Promise<InvestmentConnectionNode>,
    Fragmentable {
  pageInfo: <T = PageInfo>() => T;
  edges: <T = Promise<Array<InvestmentEdgeNode>>>() => T;
  aggregate: <T = AggregateInvestment>() => T;
}

export interface InvestmentConnectionSubscription
  extends Promise<AsyncIterator<InvestmentConnectionNode>>,
    Fragmentable {
  pageInfo: <T = PageInfoSubscription>() => T;
  edges: <T = Promise<AsyncIterator<Array<InvestmentEdgeSubscription>>>>() => T;
  aggregate: <T = AggregateInvestmentSubscription>() => T;
}

export interface InvestmentPreviousValuesNode {
  id: ID_Output;
  address: String;
  price?: Float;
  monthly_rent?: Float;
  mortgage_downpayment?: Float;
  mortgage_amount?: Float;
  mortgage_interest_rate?: Float;
  mortgage_period?: Float;
}

export interface InvestmentPreviousValues
  extends Promise<InvestmentPreviousValuesNode>,
    Fragmentable {
  id: () => Promise<ID_Output>;
  address: () => Promise<String>;
  price: () => Promise<Float>;
  monthly_rent: () => Promise<Float>;
  mortgage_downpayment: () => Promise<Float>;
  mortgage_amount: () => Promise<Float>;
  mortgage_interest_rate: () => Promise<Float>;
  mortgage_period: () => Promise<Float>;
}

export interface InvestmentPreviousValuesSubscription
  extends Promise<AsyncIterator<InvestmentPreviousValuesNode>>,
    Fragmentable {
  id: () => Promise<AsyncIterator<ID_Output>>;
  address: () => Promise<AsyncIterator<String>>;
  price: () => Promise<AsyncIterator<Float>>;
  monthly_rent: () => Promise<AsyncIterator<Float>>;
  mortgage_downpayment: () => Promise<AsyncIterator<Float>>;
  mortgage_amount: () => Promise<AsyncIterator<Float>>;
  mortgage_interest_rate: () => Promise<AsyncIterator<Float>>;
  mortgage_period: () => Promise<AsyncIterator<Float>>;
}

export interface InvestmentSubscriptionPayloadNode {
  mutation: MutationType;
  updatedFields?: String[];
}

export interface InvestmentSubscriptionPayload
  extends Promise<InvestmentSubscriptionPayloadNode>,
    Fragmentable {
  mutation: () => Promise<MutationType>;
  node: <T = Investment>() => T;
  updatedFields: () => Promise<String[]>;
  previousValues: <T = InvestmentPreviousValues>() => T;
}

export interface InvestmentSubscriptionPayloadSubscription
  extends Promise<AsyncIterator<InvestmentSubscriptionPayloadNode>>,
    Fragmentable {
  mutation: () => Promise<AsyncIterator<MutationType>>;
  node: <T = InvestmentSubscription>() => T;
  updatedFields: () => Promise<AsyncIterator<String[]>>;
  previousValues: <T = InvestmentPreviousValuesSubscription>() => T;
}

export interface InvestmentNode {
  id: ID_Output;
  address: String;
  price?: Float;
  monthly_rent?: Float;
  mortgage_downpayment?: Float;
  mortgage_amount?: Float;
  mortgage_interest_rate?: Float;
  mortgage_period?: Float;
}

export interface Investment extends Promise<InvestmentNode>, Fragmentable {
  id: () => Promise<ID_Output>;
  address: () => Promise<String>;
  price: () => Promise<Float>;
  monthly_rent: () => Promise<Float>;
  mortgage_downpayment: () => Promise<Float>;
  mortgage_amount: () => Promise<Float>;
  mortgage_interest_rate: () => Promise<Float>;
  mortgage_period: () => Promise<Float>;
}

export interface InvestmentSubscription
  extends Promise<AsyncIterator<InvestmentNode>>,
    Fragmentable {
  id: () => Promise<AsyncIterator<ID_Output>>;
  address: () => Promise<AsyncIterator<String>>;
  price: () => Promise<AsyncIterator<Float>>;
  monthly_rent: () => Promise<AsyncIterator<Float>>;
  mortgage_downpayment: () => Promise<AsyncIterator<Float>>;
  mortgage_amount: () => Promise<AsyncIterator<Float>>;
  mortgage_interest_rate: () => Promise<AsyncIterator<Float>>;
  mortgage_period: () => Promise<AsyncIterator<Float>>;
}

export interface ProviderPreviousValuesNode {
  id: ID_Output;
  name: String;
  type: String;
  rate?: Float;
  review_number?: Int;
  review?: String;
  phone_number?: String;
  email?: String;
  addr1?: String;
  addr2?: String;
}

export interface ProviderPreviousValues
  extends Promise<ProviderPreviousValuesNode>,
    Fragmentable {
  id: () => Promise<ID_Output>;
  name: () => Promise<String>;
  type: () => Promise<String>;
  rate: () => Promise<Float>;
  review_number: () => Promise<Int>;
  review: () => Promise<String>;
  phone_number: () => Promise<String>;
  email: () => Promise<String>;
  addr1: () => Promise<String>;
  addr2: () => Promise<String>;
}

export interface ProviderPreviousValuesSubscription
  extends Promise<AsyncIterator<ProviderPreviousValuesNode>>,
    Fragmentable {
  id: () => Promise<AsyncIterator<ID_Output>>;
  name: () => Promise<AsyncIterator<String>>;
  type: () => Promise<AsyncIterator<String>>;
  rate: () => Promise<AsyncIterator<Float>>;
  review_number: () => Promise<AsyncIterator<Int>>;
  review: () => Promise<AsyncIterator<String>>;
  phone_number: () => Promise<AsyncIterator<String>>;
  email: () => Promise<AsyncIterator<String>>;
  addr1: () => Promise<AsyncIterator<String>>;
  addr2: () => Promise<AsyncIterator<String>>;
}

export interface UserSubscriptionPayloadNode {
  mutation: MutationType;
  updatedFields?: String[];
}

export interface UserSubscriptionPayload
  extends Promise<UserSubscriptionPayloadNode>,
    Fragmentable {
  mutation: () => Promise<MutationType>;
  node: <T = User>() => T;
  updatedFields: () => Promise<String[]>;
  previousValues: <T = UserPreviousValues>() => T;
}

export interface UserSubscriptionPayloadSubscription
  extends Promise<AsyncIterator<UserSubscriptionPayloadNode>>,
    Fragmentable {
  mutation: () => Promise<AsyncIterator<MutationType>>;
  node: <T = UserSubscription>() => T;
  updatedFields: () => Promise<AsyncIterator<String[]>>;
  previousValues: <T = UserPreviousValuesSubscription>() => T;
}

export interface ProviderEdgeNode {
  cursor: String;
}

export interface ProviderEdge extends Promise<ProviderEdgeNode>, Fragmentable {
  node: <T = Provider>() => T;
  cursor: () => Promise<String>;
}

export interface ProviderEdgeSubscription
  extends Promise<AsyncIterator<ProviderEdgeNode>>,
    Fragmentable {
  node: <T = ProviderSubscription>() => T;
  cursor: () => Promise<AsyncIterator<String>>;
}

export interface AggregateProviderNode {
  count: Int;
}

export interface AggregateProvider
  extends Promise<AggregateProviderNode>,
    Fragmentable {
  count: () => Promise<Int>;
}

export interface AggregateProviderSubscription
  extends Promise<AsyncIterator<AggregateProviderNode>>,
    Fragmentable {
  count: () => Promise<AsyncIterator<Int>>;
}

export interface ProviderNode {
  id: ID_Output;
  name: String;
  type: String;
  rate?: Float;
  review_number?: Int;
  review?: String;
  phone_number?: String;
  email?: String;
  addr1?: String;
  addr2?: String;
}

export interface Provider extends Promise<ProviderNode>, Fragmentable {
  id: () => Promise<ID_Output>;
  name: () => Promise<String>;
  type: () => Promise<String>;
  rate: () => Promise<Float>;
  review_number: () => Promise<Int>;
  review: () => Promise<String>;
  phone_number: () => Promise<String>;
  email: () => Promise<String>;
  addr1: () => Promise<String>;
  addr2: () => Promise<String>;
}

export interface ProviderSubscription
  extends Promise<AsyncIterator<ProviderNode>>,
    Fragmentable {
  id: () => Promise<AsyncIterator<ID_Output>>;
  name: () => Promise<AsyncIterator<String>>;
  type: () => Promise<AsyncIterator<String>>;
  rate: () => Promise<AsyncIterator<Float>>;
  review_number: () => Promise<AsyncIterator<Int>>;
  review: () => Promise<AsyncIterator<String>>;
  phone_number: () => Promise<AsyncIterator<String>>;
  email: () => Promise<AsyncIterator<String>>;
  addr1: () => Promise<AsyncIterator<String>>;
  addr2: () => Promise<AsyncIterator<String>>;
}

/*
The `Boolean` scalar type represents `true` or `false`.
*/
export type Boolean = boolean;

/*
The `ID` scalar type represents a unique identifier, often used to refetch an object or as key for a cache. The ID type appears in a JSON response as a String; however, it is not intended to be human-readable. When expected as an input type, any string (such as `"4"`) or integer (such as `4`) input value will be accepted as an ID.
*/
export type ID_Input = string | number;
export type ID_Output = string;

/*
The `Float` scalar type represents signed double-precision fractional values as specified by [IEEE 754](http://en.wikipedia.org/wiki/IEEE_floating_point). 
*/
export type Float = number;

/*
The `String` scalar type represents textual data, represented as UTF-8 character sequences. The String type is most often used by GraphQL to represent free-form human-readable text.
*/
export type String = string;

/*
The `Int` scalar type represents non-fractional signed whole numeric values. Int can represent values between -(2^31) and 2^31 - 1. 
*/
export type Int = number;

export type Long = string;

/**
 * Type Defs
 */

export const Prisma = makePrismaClientClass<ClientConstructor<Prisma>>({
  typeDefs,
  endpoint: `${process.env["PRISMA_ENDPOINT"]}`
});
export const prisma = new Prisma();
